{
 "title": "Aeron Stats",
 "time": { "from": "2018-10-18T08:01:39.900Z", "to": "2018-10-18T10:14:51.390Z" },
 "panels": [
  {
   "title": "Num Subscribers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_subscribers" }
   ]
  },
  {
   "title": "Num Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_clients" }
   ]
  },
  {
   "title": "Num_channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_channel" }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bytes_sent" }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bytes_received" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "errors" }
   ]
  }
 ]
}