{
 "title": "Aeron Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Num Subscribers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_subscribers{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Num Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_clients{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Num_channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_channel{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bytes_sent_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bytes_received_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "errors_total{}", "legendFormat": "__auto" }
   ]
  }
 ]
}